INSERT INTO CUSTOMER (ID, FIRSTNAME, LASTNAME) VALUES (1,'Phil','Bross');
INSERT INTO CUSTOMER (ID, FIRSTNAME, LASTNAME) VALUES (2,'John','Doe');
INSERT INTO CUSTOMER (ID, FIRSTNAME, LASTNAME) VALUES (3,'Zinedine','Zidane');
COMMIT;
