ALTER TABLE testschema.CUSTOMER ADD COLUMN CUSTOMER_TYPE VARCHAR(50);
UPDATE testschema.CUSTOMER SET CUSTOMER_TYPE='NONSUBSCRIBER';
COMMIT;

ALTER TABLE testschema.CUSTOMER ADD COLUMN VOUCHER_CODE VARCHAR(50);
UPDATE testschema.CUSTOMER SET VOUCHER_CODE='INIT2016';
COMMIT;

ALTER TABLE testschema.CUSTOMER ADD COLUMN START_DATE bigint;
ALTER TABLE testschema.CUSTOMER ADD COLUMN END_DATE bigint;