ALTER TABLE testschema.CUSTOMER DROP COLUMN CUSTOMER_TYPE;
ALTER TABLE testschema.CUSTOMER DROP COLUMN VOUCHER_CODE;
ALTER TABLE testschema.CUSTOMER DROP COLUMN START_DATE;
ALTER TABLE testschema.CUSTOMER DROP COLUMN END_DATE;

CREATE SEQUENCE PRODUCTID_SEQ_GEN
  INCREMENT 1
  MINVALUE 1
  MAXVALUE 2147483647
  START 1
  CACHE 10;

CREATE TABLE testschema.PRODUCT (
    ID integer NOT NULL PRIMARY KEY DEFAULT nextval('testschema.PRODUCTID_SEQ_GEN'),
    NAME VARCHAR(50) NOT NULL,
    CREATED  bigint NOT NULL,
    CREATED_BY VARCHAR(50) NOT NULL,
    MODIFIED bigint NOT NULL,
    MODIFIED_BY VARCHAR(50) NOT NULL,
    VERSION integer NOT NULL,
    MAP_CODE VARCHAR(50),
    START_DATE bigint,
    END_DATE bigint,
    PRODUCT_TYPE VARCHAR(50)
);