DROP DATABASE IF EXISTS teststore;
DROP USER IF EXISTS teststore;

CREATE ROLE teststore PASSWORD 'teststore' NOSUPERUSER NOCREATEDB NOCREATEROLE INHERIT LOGIN;

CREATE DATABASE teststore WITH OWNER = teststore ENCODING = 'UTF8';

\c teststore;

CREATE SCHEMA teststore AUTHORIZATION teststore;

GRANT CONNECT ON DATABASE teststore TO teststore;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA teststore TO teststore;
